apiVersion: 1

datasources:
  - name: System Metrics
    type: marcusolsson-json-datasource
    uid: visual-eyes-system
    url: http://localhost:8080
    access: proxy
    isDefault: true
    jsonData:
      timeField: "timestamp"
      queryParams: []
    version: 1
    editable: true

  - name: Kubernetes Metrics
    type: marcusolsson-json-datasource
    uid: visual-eyes-k8s
    url: http://192.168.24.203:8080
    access: proxy
    jsonData:
      timeField: "timestamp"
      queryParams: []
    version: 1
    editable: true 