apiVersion: v1
kind: ServiceAccount
metadata:
  name: visual-eyes-agent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: visual-eyes-agent
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics", "nodes/stats", "nodes/proxy"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: visual-eyes-agent
subjects:
- kind: ServiceAccount
  name: visual-eyes-agent
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: visual-eyes-agent
  apiGroup: rbac.authorization.k8s.io 